### ISSUE TITLE
working implementation

### ISSUE THREAD

**Issue by michaelhitzker** [htl-perg-2019-20-5bhif/bike-rental-exercise-michaelhitzker#1]
Dear Mr. Stropek!

I have implemented all the requirements, but only wrote Unit Tests for the price calculation logic. I tried hosting it on Azure, but when I try to click on "Claim your Azure credit now", I always get redirected back to that page and never get access to Azure's student credits.

Kind regards
Michael Hitzker

**Comment by rstropek** [comment]
Hi @michaelhitzker!

One extra point is yours. If you want, we can try to claim your Azure benefits together in one of the next lessons.

Greetings,
Rainer Stropek.
